import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import sharp from 'sharp';
import { optimize } from 'svgo';

const path = (relative) =>
  fileURLToPath(new URL(`../${relative}`, import.meta.url));

const SVG_SOURCES = {
  'logo-wordmark': 'LOGOTYPE/BASIC/ENCRE/SANS_LOGOMARK/LOGO_APHRA_ENCORE.svg',
  'logo-wordmark-moon':
    'LOGOTYPE/BASIC/ENCRE/AVEC_LOGOMARK/LOGO_APHRA_ENCRE.svg',
  ...Object.fromEntries(
    [1, 2, 3, 4, 5, 6].map((n) => [
      `logomark-${n}`,
      `LOGOMARK/BASIC/${n}/ENCRE/LOGOMARK_${n}_ENCRE.svg`,
    ]),
  ),
};
const ILLUSTRATIONS = ['concombre', 'mangue', 'pomme', 'poivron', 'tomate'];
const SOURCE_INK = /#162419/gi;
const MAX_WIDTH = 1920;
const SPECK_SHARE = 0.01;
const NEIGHBOURS = [-1, 0, 1].flatMap((dy) => [-1, 0, 1].map((dx) => [dx, dy]));

async function buildSvg(name, source) {
  const raw = await readFile(path(`sources/${source}`), 'utf8');
  const { data } = optimize(raw.replace(SOURCE_INK, 'currentColor'), {
    path: source,
    multipass: true,
  });
  await writeFile(path(`assets/${name}.svg`), `${data}\n`);
}

function pieces(alpha, width, height) {
  const seen = new Uint8Array(alpha.length);
  const stack = new Int32Array(alpha.length);
  const found = [];
  for (let start = 0; start < alpha.length; start++) {
    if (alpha[start] === 0 || seen[start]) continue;
    const piece = { area: 0, left: width, top: height, right: 0, bottom: 0 };
    let depth = 0;
    stack[depth++] = start;
    seen[start] = 1;
    while (depth > 0) {
      const index = stack[--depth];
      const x = index % width;
      const y = (index - x) / width;
      piece.area += 1;
      piece.left = Math.min(piece.left, x);
      piece.right = Math.max(piece.right, x);
      piece.top = Math.min(piece.top, y);
      piece.bottom = Math.max(piece.bottom, y);
      for (const [dx, dy] of NEIGHBOURS) {
        const nx = x + dx;
        const ny = y + dy;
        if (nx < 0 || ny < 0 || nx >= width || ny >= height) continue;
        const next = ny * width + nx;
        if (alpha[next] === 0 || seen[next]) continue;
        seen[next] = 1;
        stack[depth++] = next;
      }
    }
    found.push(piece);
  }
  return found;
}

// Stray alpha specks defeat sharp trim(): only the large pieces set the box.
async function artworkBox(file) {
  const { data, info } = await sharp(file)
    .ensureAlpha()
    .extractChannel('alpha')
    .raw()
    .toBuffer({ resolveWithObject: true });
  const found = pieces(data, info.width, info.height);
  const largest = Math.max(...found.map((piece) => piece.area));
  const kept = found.filter((piece) => piece.area >= largest * SPECK_SHARE);
  const left = Math.min(...kept.map((piece) => piece.left));
  const top = Math.min(...kept.map((piece) => piece.top));
  const right = Math.max(...kept.map((piece) => piece.right));
  const bottom = Math.max(...kept.map((piece) => piece.bottom));
  return { left, top, width: right - left + 1, height: bottom - top + 1 };
}

async function trimmed(source) {
  const file = path(`sources/${source}`);
  const original = await sharp(file).metadata();
  const box = await artworkBox(file);
  if (box.width === original.width && box.height === original.height) {
    throw new Error(`${source}: trim removed nothing`);
  }
  return sharp(file).extract(box).toBuffer();
}

async function buildIllustration(name) {
  const image = await trimmed(`ICONO/ILLUS_${name.toUpperCase()}.png`);
  for (const width of [480, 960]) {
    await sharp(image)
      .resize({ width })
      .webp({ quality: 82 })
      .toFile(path(`assets/illustration-${name}-${width}.webp`));
  }
  const full = await sharp(image)
    .resize({ width: MAX_WIDTH, withoutEnlargement: true })
    .webp({ quality: 82 })
    .toFile(path(`assets/illustration-${name}-full.webp`));
  return `  ${name}: { width: ${full.width}, height: ${full.height} },`;
}

async function buildStamp() {
  const image = await trimmed('LOGOMARK/TAMPON/LOGOMARK_TAMPON_1.png');
  const info = await sharp(image)
    .resize({ width: 800, withoutEnlargement: true })
    .webp({ quality: 85 })
    .toFile(path('assets/logomark-stamp.webp'));
  return `export const STAMP_SIZE = { width: ${info.width}, height: ${info.height} } as const;`;
}

await mkdir(path('assets'), { recursive: true });
await mkdir(path('src/generated'), { recursive: true });
await Promise.all(
  Object.entries(SVG_SOURCES).map(([name, source]) => buildSvg(name, source)),
);
const illustrations = [];
for (const name of ILLUSTRATIONS)
  illustrations.push(await buildIllustration(name));
const stamp = await buildStamp();
await writeFile(
  path('src/generated/asset-sizes.ts'),
  [
    '// Generated by scripts/build-assets.mjs. Run `npm run assets` to update.',
    'export const ILLUSTRATION_SIZES = {',
    ...illustrations,
    '} as const;',
    '',
    stamp,
    '',
  ].join('\n'),
);
